version: "2.1"
services:
  oauth:
    image: "docker.hunantv.com/huyinghuan/oauth:latest"
    container_name: "oauth"
    restart: always
    ports: 
      - "8000:8000"
    environment:
      - OPENAUTH_DEBUG=false
      #admin account username
      - OPENAUTH_ADMIN=admin
      #admin account password
      - OPENAUTH_ADMIN_PASS=12345678
      - OPENAUTH_ADMIN_RESET_ONRESTART=true
      #account database mysql
      - OPENAUTH_DATABASE=root:12345678@tcp(mysql:3306)/oauth
      #redis
      - OPENAUTH_REDIS_CLIENT_ADDR=redis:6379
      #- OPENAUTH_REDIS_CLIENT_PASS=
      #- OPENAUTH_REDIS_CLIENT_DB=
      - OPENAUTH_OPEN_REGISTER=true
      - OPENAUTH_OPEN_APP_REGISTER=true
      - OPENAUTH_REDIS_CACHE_FROM_DB=true
    networks: 
      oauth:
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
  mysql:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: oauth
    volumes:
      - /Volumes/Macintosh HD/Extends/data/mysql-oauth:/var/lib/mysql
      - ./sql/table.sql:/docker-entrypoint-initdb.d/table.sql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=12345678 --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      oauth:
  redis:
    image: redis:latest
    restart: always
    volumes:
      - /Volumes/Macintosh HD/Extends/data/redis-oauth:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      oauth:
networks: 
  oauth:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.96.0/24 
          gateway: 172.16.96.1
