-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 09:57:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oauth
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oauth` DEFAULT CHARACTER SET utf8 ;
USE `oauth` ;

-- -----------------------------------------------------
-- Table `oauth`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(100) NOT NULL DEFAULT 'default' COMMENT '账户名',
  `password` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '密码',
  `nickname` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '昵称',
  `email` VARCHAR(245) NOT NULL DEFAULT 'default' COMMENT '邮箱',
  `avater` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '头像',
  `created_at` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户表';


-- -----------------------------------------------------
-- Table `oauth`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth`.`application` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '用户id',
  `name` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '应用名称',
  `client_id` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '客户端ID',
  `private_key` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '客户端私钥',
  `callback` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '客户端回调地址',
  `mode` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '客户端运行模式',
  `open` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '应用表';


-- -----------------------------------------------------
-- Table `oauth`.`app_user_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth`.`app_user_list` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '用户id',
  `app_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '应用id',
  `category` VARCHAR(255) NOT NULL DEFAULT 'black' COMMENT '黑白名单',
  `role_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '角色id',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '应用的用户列表';


-- -----------------------------------------------------
-- Table `oauth`.`app_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth`.`app_role` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `app_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '应用id',
  `name` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '角色名称',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '应用的角色信息表';


-- -----------------------------------------------------
-- Table `oauth`.`app_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `oauth`.`app_role_permission` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `role_id` BIGINT(20) NOT NULL DEFAULT 0 COMMENT '角色id',
  `name` VARCHAR(255) NOT NULL DEFAULT 'default' COMMENT '权限别称',
  `method` VARCHAR(45) NOT NULL DEFAULT 'GET' COMMENT 'HTTP方法',
  `pattern` VARCHAR(255) NOT NULL DEFAULT '*' COMMENT '路径匹配正则',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniq_id` (`id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '应用角色的权限列表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
